### ISSUE TITLE
Datasets are missing.

### ISSUE THREAD

**Issue by mehrdadh** [eembc/energyrunner#17]
Hi,

Is there a reason that `datasets/ad0/` and other datasets only have y labels and not the actual sample files?

Thanks.

**Comment by petertorelli** [comment]
Hi @mehrdadh,
Yes, the datasets were removed because we don't have the rights to re-distribute them. There is an action item for each owner to provide instructions as to where to find the input files. (I think technically they are still in older branches which can get you by for now, but they eventually need to be purged...). You can also ping @cskiraly .

Peter

**Comment by sahelib25** [comment]
Hi, 
I am struggling to get the binary input files for EEMBC energy runner. Can you please help me with this?

**Comment by petertorelli** [comment]
Please contact the MLCommons MLPerf Tiny working group. They host the input binary files.
