### ISSUE TITLE
Is `Ground Truth` in `datasets/vww01/y_labels.csv` correct?

### ISSUE THREAD

**Issue by xlindo** [eembc/energyrunner#25]
No problem.

Please delete this issue. @petertorelli

**Comment by petertorelli** [comment]
Interesting, thanks for filing this bug.

@cskiraly This looks like a question for the MLPerfTiny working group.

**Comment by xlindo** [comment]
> Interesting, thanks for filing this bug.
> 
> @cskiraly This looks like a question for the MLPerfTiny working group.

It is my fault. The fingers or legs are also involved. So it is correct.

**Comment by petertorelli** [comment]
@xlindo 
I'll keep it in the "closed" archive because I think that is a helpful observation. I thought "person" meant "full canonical biped", it would not occur to me that hand = person. But perhaps if the person-detector is used for controlling a CNC emergency shutoff if a person enters the frame, then a hand would certainly be an important thing to classify!

Peter
